// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgplcbcyimzydtaiwwii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtncGxjYmN5aW16eWR0YWl3d2lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MjE2NTMsImV4cCI6MjA3MjI5NzY1M30.XW_zHa8QKctHGZflXGzujIfqRKtb6npqSkRpyr8xpXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});