// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sykwhebtcakotknlkwfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5a3doZWJ0Y2Frb3Rrbmxrd2ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMzY3ODUsImV4cCI6MjA2OTYxMjc4NX0.Hl1a5iKbMhJb8E4MGYaSgxEJK3lSY7R9DxEKLXEchSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});